# Site settings
title: My Sample Jekyll Site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-101/gh-pages/assets/jekyll-website-sample/_site" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maptimeboulder

# Build settings
markdown: kramdown
